### ISSUE TITLE
Julia 언어 예제

### ISSUE THREAD

**Issue by YongHee-Kim** [hatemogi/hangul-coding.net#1]
안녕하세요
한글 코딩을 사랑하는 동지(?)로써 반갑습니다. 

저는 [Julia](http://docs.julialang.org/en/stable/) 언어로 게임 밸런싱 시뮬레이션을 만드는데, 팀 없이 혼자하는 작업이고 게임의 소스코드를 보는게 아니라 UI나 기획서를 보면서 작업하다보니 한글로 코드를 짜게되는데 대표적인 예제는 아래와 같습니다.

``` Julia
function 아이템강화비용(x::Item)
    ref = @where(ITEM_COST[x.class], :Rank .== x.rank, :Enchant .== x.enchant)
    cost = ref[1, :Cost_Currency]
    return cost
end

function 아이템강화!(ac::Account, x::Item)
    if remove!(ac, 아이템강화비용(x))
        아이템강화!(x)
    end
end
```

저 같은 경우 모바일 게임에서 자주 쓰이는 용어들 `"강화", "승급", "진화"`을, 영어로 쓰면 헷갈리는 일이 많아서 한글 코딩을 하게되었습니다.

**Comment by hatemogi** [comment]
오! 반갑습니다.
